#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=PERTU-P
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load OpenMPI/4.1.5-NVHPC-24.5-CUDA-12.1.1
module load Anaconda3/2023.07-2
source activate fact

srun python perturbation_test.py --method lrp --mode pos --subset 40 --radii 2 --masks 2